<?php
declare (strict_types=1);

namespace app\console\controller;

use app\common\controller\ConsoleBase;
use app\common\model\Module;

class Index extends ConsoleBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if ($this->request->action(true) == 'index') {
            $this->layout = 'layout';
            $this->view->layout('layout');
        }
    }

    public function index()
    {

        return $this->fetch();
    }

    public function welcome()
    {
        return $this->fetch();
    }
}
